### ISSUE TITLE
xpose报错，是微信做了检查？

### ISSUE THREAD

**Issue by gdchaochao** [zhengmin1989/WechatSportCheat#1]
试了一下，发现报如下的错误，是不是微信加了些什么检查机制呢？

10-11 22:45:38.514: I/Xposed(2041): java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.MiuiTypedArray to class android.content.res.XResources$XTypedArray
10-11 22:45:38.514: I/Xposed(2041):     at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
10-11 22:45:38.514: I/Xposed(2041):     at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
10-11 22:45:38.514: I/Xposed(2041):     at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
10-11 22:45:38.514: I/Xposed(2041):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.res.TypedArray.<init>(Native Method)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.res.MiuiTypedArray.<init>(MiuiTypedArray.java:13)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.res.Resources.getCachedStyledAttributes(Resources.java:2424)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.res.Resources.access$000(Resources.java:76)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:1379)
10-11 22:45:38.514: I/Xposed(2041):     at android.content.Context.obtainStyledAttributes(Context.java:427)
10-11 22:45:38.514: I/Xposed(2041):     at android.view.View.<init>(View.java:3511)
10-11 22:45:38.514: I/Xposed(2041):     at android.view.ViewGroup.<init>(ViewGroup.java:470)
10-11 22:45:38.514: I/Xposed(2041):     at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:52)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.smtt.webkit.WebView.<init>(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.smtt.webkit.adapter.X5WebViewAdapter.<init>(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Constructor.constructNative(Native Method)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.tbs.tbsshell.WebCoreProxy.createSDKWebViewInstance(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.tbs.x5core.WebViewPool.acquireWebView(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.tbs.tbsshell.WebCoreProxy.createSDKWebview(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Method.invokeNative(Native Method)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Method.invoke(Method.java:515)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.smtt.export.external.DexLoader.invokeStaticMethod(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.smtt.sdk.ab.fN(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at com.tencent.smtt.sdk.QbSdk$2.handleMessage(Unknown Source)
10-11 22:45:38.514: I/Xposed(2041):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-11 22:45:38.514: I/Xposed(2041):     at android.os.Looper.loop(Looper.java:136)
10-11 22:45:38.514: I/Xposed(2041):     at android.app.ActivityThread.main(ActivityThread.java:5047)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Method.invokeNative(Native Method)
10-11 22:45:38.514: I/Xposed(2041):     at java.lang.reflect.Method.invoke(Method.java:515)
10-11 22:45:38.514: I/Xposed(2041):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
10-11 22:45:38.514: I/Xposed(2041):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
10-11 22:45:38.514: I/Xposed(2041):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-11 22:45:38.514: I/Xposed(2041):     at dalvik.system.NativeStart.main(Native Method)

**Comment by artemiseven** [comment]
我也报了这个错 ,请问你那边解决了吗?

**Comment by imlk0** [comment]
MIUI
